- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present

- name: Allow HTTP/HTTPS ports - Influx and Grafana
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - { port: 3000, proto: tcp }
    - { port: 8086, proto: tcp }
      
- name: Enable UFW
  ufw:
    state: enabled

- name: Reload UFW
  ufw:
    state: reloaded

- name: Ensure UFW is started at boot
  service:
    name: ufw
    enabled: yes
    state: started
