---
  - name: Create /opt/kafka/logs directory
    ansible.builtin.file:
      path: /opt/kafka/logs
      state: directory

  - name: Set log/data directory in server.properties
    lineinfile:
      path: /opt/kafka/config/kraft/server.properties
      regexp: '^log.dirs=/tmp/kraft-combined-logs'
      line: 'log.dirs=/opt/kafka/logs'

  - name: Check if kafka storage is formatted
    stat:
      path: /opt/kafka/logs/meta.properties
    register: register_kafka_storage

  - name: Format Kafka Storage
    shell: "/opt/kafka/bin/kafka-storage.sh format -t {{ apache_kafka_cluster_uuid }} -c /opt/kafka/config/kraft/server.properties"
    when: not register_kafka_storage.stat.exists

  - name: Set kafka retention
    lineinfile:
      path: /opt/kafka/config/kraft/server.properties
      regexp: '^log.retention.hours='
      line: 'log.retention.hours=1'

  - name: Set kafka listeners
    lineinfile:
      path: /opt/kafka/config/kraft/server.properties
      regexp: '^listeners='
      line: 'listeners=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9095'

  - name: Set kafka advertised listeners
    lineinfile:
      path: /opt/kafka/config/kraft/server.properties
      regexp: '^advertised.listeners='
      line: 'advertised.listeners=PLAINTEXT://192.168.1.116:9092,EXTERNAL://65.21.29.20:9095'

  - name: Set kafka advertised listeners
    lineinfile:
      path: /opt/kafka/config/kraft/server.properties
      regexp: '^listener.security.protocol.map='
      line: 'listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL,EXTERNAL:PLAINTEXT'

  - name: Copy systemd unit file
    ansible.builtin.copy:
      src: kafka.service
      dest: /etc/systemd/system/kafka.service
    register: kafka_service

  - name: Reload systemd
    ansible.builtin.systemd_service:
      daemon_reload: true
    when: kafka_service.changed

  - name: Enable and start Kafka service
    systemd:
      name: kafka
      enabled: yes
      state: started
