- name: Install required packages
  apt:
    pkg:
      - curl
      - wget
      - unzip
      - wordpress
    state: latest
    update_cache: true

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no

- name: Create Document Root
  ansible.builtin.file:
    path: "{{ wordpress_documentroot }}"
    state: directory

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: "{{ wordpress_documentroot }}"
    #creates: "{{ wordpress_documentroot }}/wp-admin"
    copy: no
    extra_opts: [--strip-components=1]

- name: Generate wp-config.php file
  template:
    src: templates/wp-config.php.j2
    dest: "{{ wordpress_documentroot }}/wp-config.php"
    mode: '0640'
    owner: www-data
    group: www-data

- name: Set permissions to files and folders
  file:
    path: "{{ wordpress_documentroot }}"
    owner: www-data
    group: www-data
    recurse: yes

- name: Set permissions for directories
  shell: "/usr/bin/find {{ wordpress_documentroot }} -type d -exec chmod 750 {} \\;"

- name: Set permissions for files
  shell: "/usr/bin/find {{ wordpress_documentroot }} -type f -exec chmod 640 {} \\;"
