- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present

- name: Allow Elasticsearch (port 9200)
  ufw:
    rule: allow
    port: 9200
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled

- name: Reload UFW
  ufw:
    state: reloaded

- name: Ensure UFW is started at boot
  service:
    name: ufw
    enabled: yes
    state: started
