- name: Ensure UFW is installed
  apt:
    name: ufw
    state: present

- name: Allow HTTP/HTTPS ports
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - { port: 389, proto: udp }
    - { port: 389, proto: tcp }
    - { port: 80, proto: tcp }
    - { port: 443, proto: tcp }

- name: Enable UFW
  ufw:
    state: enabled

- name: Reload UFW
  ufw:
    state: reloaded

- name: Ensure UFW is started at boot
  service:
    name: ufw
    enabled: yes
    state: started
