- name: Run Kibana Enrollment Token Command
  shell: /usr/share/kibana/bin/kibana-setup --enrollment-token {{ hostvars['elasticsearch.greypixel.nl']['enrollment_token'] }}
  args:
    stdin: "y\n"
  when: hostvars['elasticsearch.greypixel.nl']['enrollment_token'] is defined

- name: Display all variables/facts known for a host
  ansible.builtin.debug:
    var: hostvars['elasticsearch.greypixel.nl']
    verbosity: 4

- name: Ensure server.host 0.0.0.0 is set in kibana.yml
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#?server\.host: 0.0.0.0'
    line: 'server.host: 0.0.0.0'
    state: present

- name: Enable and start kibana service
  service:
    name: kibana
    state: restarted
    enabled: yes
